# Generated by Django 3.1.7 on 2021-03-10 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopKeeper', '0002_auto_20210303_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='product_pics'),
        ),
    ]
