# Generated by Django 3.1.7 on 2021-03-18 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopKeeper', '0004_products_product_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='product_unit',
        ),
    ]
