# Generated by Django 3.1.7 on 2021-03-28 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopKeeper', '0005_remove_products_product_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_unit',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
